print("A mamãe gritou:")
print("qua "*4)
print("mas nenhum patinho voltou de lá...")
print(" ")
print("Sete elefantes incomodam muita gente. Oito elefantes -")
print("incomodam..."*8)
print("muito mais!")
print(" ")
print("Pa"+"ra"+"le"*2+"pí"+"pe"+"do")
